version: '3' # composeファイルのバーション指定
services:
  golang: 
    build: ./docker/
    tty: true
    volumes:
      - ./GOPATH/src:/go/src
      - ./GOPATH/pkg:/go/pkg
      - ./GOPATH/bin:/go/bin
      - ./src:/src
